# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ce026563e8754b5e3ef6ee5c3693057c6ceaabd7eae31b9e3ae400ae139f818f34a95a6aa552217e652ae84d4956499d76df9fd488ede1fa631f2f5b4f1127e

test:
  secret_key_base: bf487d41b5107c10e125678f9ef032d448e234b6bdbb6df1bac78a1fc829e2a84deb2a566a9a901a37f2e4b99a814d45b4a2f79bc43c5985d14f421547e2e47d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
